/* ============================================================
 * DESIGN: Neon Vinyl Lounge — Retro-futuristic jukebox
 * Each genre has its own neon color signature
 * ============================================================ */

const CDN = "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031543551";

export interface Track {
  id: string;
  title: string;
  style: string;
  language: string;
  flag: string;
  country: string;
  neonColor: string;
  neonColorRgb: string;
  audioUrl: string;
  audioUrlAlt: string;
  theme: "se-olha" | "viva";
}

export const THEMES = {
  "se-olha": {
    id: "se-olha",
    title: "Se Olha",
    subtitle: "Amor-próprio & Reflexão",
    description: "Músicas que te fazem parar e olhar pra dentro. Cada estilo traz a mensagem de se amar de um jeito diferente.",
    icon: "💎",
  },
  "viva": {
    id: "viva",
    title: "Viva!",
    subtitle: "Diversão & Festa",
    description: "Músicas pra dançar e rir — mas com aquele verso escondido que te pega de surpresa e te faz refletir.",
    icon: "🎉",
  },
};

export const tracks: Track[] = [
  // ========== TEMA 1: SE OLHA ==========
  {
    id: "bossa-nova-pt",
    title: "Se Ama",
    style: "Bossa Nova",
    language: "Português",
    flag: "🇧🇷",
    country: "Brasil",
    neonColor: "#00e676",
    neonColorRgb: "0, 230, 118",
    audioUrl: `${CDN}/ByxRZKkxeLpgQzut.mp3`,
    audioUrlAlt: `${CDN}/PFIkNsqXmYJwffuH.mp3`,
    theme: "se-olha",
  },
  {
    id: "rock-en",
    title: "Love Yourself",
    style: "Rock",
    language: "English",
    flag: "🇺🇸",
    country: "USA",
    neonColor: "#ff1744",
    neonColorRgb: "255, 23, 68",
    audioUrl: `${CDN}/TtvVtkfChByZUKll.mp3`,
    audioUrlAlt: `${CDN}/WyMtnTIpLdKPZCYO.mp3`,
    theme: "se-olha",
  },
  {
    id: "reggaeton-es",
    title: "Quiérete",
    style: "Reggaeton",
    language: "Español",
    flag: "🇪🇸",
    country: "Espanha",
    neonColor: "#ff9100",
    neonColorRgb: "255, 145, 0",
    audioUrl: `${CDN}/pXswxRgsUVSomxDH.mp3`,
    audioUrlAlt: `${CDN}/hMOTXOYUOTcdaFHD.mp3`,
    theme: "se-olha",
  },
  {
    id: "chanson-fr",
    title: "Aime-toi",
    style: "Chanson",
    language: "Français",
    flag: "🇫🇷",
    country: "França",
    neonColor: "#e040fb",
    neonColorRgb: "224, 64, 251",
    audioUrl: `${CDN}/bqfHalzzeWCNWddT.mp3`,
    audioUrlAlt: `${CDN}/iPVbWAztdpFjQrQX.mp3`,
    theme: "se-olha",
  },
  {
    id: "jpop-jp",
    title: "自分を愛して",
    style: "J-Pop",
    language: "日本語",
    flag: "🇯🇵",
    country: "Japão",
    neonColor: "#ff80ab",
    neonColorRgb: "255, 128, 171",
    audioUrl: `${CDN}/GGSpeWbaIFouBAMI.mp3`,
    audioUrlAlt: `${CDN}/MvUQKpfvAgenqGpi.mp3`,
    theme: "se-olha",
  },
  {
    id: "afrobeat-en",
    title: "Love Yourself Oh",
    style: "Afrobeat",
    language: "Pidgin English",
    flag: "🇳🇬",
    country: "Nigéria",
    neonColor: "#ffd740",
    neonColorRgb: "255, 215, 64",
    audioUrl: `${CDN}/IvFOgOjKXopFNWKO.mp3`,
    audioUrlAlt: `${CDN}/UGeHjZmXvePusYXy.mp3`,
    theme: "se-olha",
  },
  {
    id: "kpop-kr",
    title: "자신을 사랑해",
    style: "K-Pop",
    language: "한국어",
    flag: "🇰🇷",
    country: "Coreia do Sul",
    neonColor: "#ea80fc",
    neonColorRgb: "234, 128, 252",
    audioUrl: `${CDN}/GycanFPVvFHBZaAB.mp3`,
    audioUrlAlt: `${CDN}/yrVZOwSkffLEZjxe.mp3`,
    theme: "se-olha",
  },
  {
    id: "reggae-en",
    title: "Love Yourself Irie",
    style: "Reggae",
    language: "English",
    flag: "🇯🇲",
    country: "Jamaica",
    neonColor: "#69f0ae",
    neonColorRgb: "105, 240, 174",
    audioUrl: `${CDN}/KeGyXKGScNKKeYFO.mp3`,
    audioUrlAlt: `${CDN}/NALMXqKIFdcbxfyy.mp3`,
    theme: "se-olha",
  },
  {
    id: "opera-it",
    title: "Amati",
    style: "Ópera",
    language: "Italiano",
    flag: "🇮🇹",
    country: "Itália",
    neonColor: "#40c4ff",
    neonColorRgb: "64, 196, 255",
    audioUrl: `${CDN}/vTHZaoASSyTlRStg.mp3`,
    audioUrlAlt: `${CDN}/URhSdFFfecQIyYip.mp3`,
    theme: "se-olha",
  },
  {
    id: "tango-ar",
    title: "Ámate",
    style: "Tango",
    language: "Español",
    flag: "🇦🇷",
    country: "Argentina",
    neonColor: "#ff5252",
    neonColorRgb: "255, 82, 82",
    audioUrl: `${CDN}/DiZoVTnwlnjuAvgk.mp3`,
    audioUrlAlt: `${CDN}/aeuoPtoMVGkudkGy.mp3`,
    theme: "se-olha",
  },
  {
    id: "electronic-ar",
    title: "أحب نفسك",
    style: "Eletrônica",
    language: "العربية",
    flag: "🇸🇦",
    country: "Arábia",
    neonColor: "#7c4dff",
    neonColorRgb: "124, 77, 255",
    audioUrl: `${CDN}/NeGiijRANHYbHMRq.mp3`,
    audioUrlAlt: `${CDN}/ofasFDiWxldMtwcb.mp3`,
    theme: "se-olha",
  },

  // ========== TEMA 2: VIVA! ==========
  {
    id: "t2-bossa-pt",
    title: "Viva a Vida",
    style: "Bossa Nova",
    language: "Português",
    flag: "🇧🇷",
    country: "Brasil",
    neonColor: "#00e676",
    neonColorRgb: "0, 230, 118",
    audioUrl: `${CDN}/MGUXIOEGPrOQCRGZ.mp3`,
    audioUrlAlt: `${CDN}/urdLNlzOPARfwCBW.mp3`,
    theme: "viva",
  },
  {
    id: "t2-rock-en",
    title: "Party Like You Mean It",
    style: "Rock",
    language: "English",
    flag: "🇺🇸",
    country: "USA",
    neonColor: "#ff1744",
    neonColorRgb: "255, 23, 68",
    audioUrl: `${CDN}/qDsvEkcOjQQZDtlT.mp3`,
    audioUrlAlt: `${CDN}/IoksBauRJcjMdnxR.mp3`,
    theme: "viva",
  },
  {
    id: "t2-reggaeton-es",
    title: "Baila Conmigo",
    style: "Reggaeton",
    language: "Español",
    flag: "🇪🇸",
    country: "Espanha",
    neonColor: "#ff9100",
    neonColorRgb: "255, 145, 0",
    audioUrl: `${CDN}/IIjYGSRRzHJWSclo.mp3`,
    audioUrlAlt: `${CDN}/jnHKxAGbsswLHNjE.mp3`,
    theme: "viva",
  },
  {
    id: "t2-chanson-fr",
    title: "Danse Ce Soir",
    style: "Chanson",
    language: "Français",
    flag: "🇫🇷",
    country: "França",
    neonColor: "#e040fb",
    neonColorRgb: "224, 64, 251",
    audioUrl: `${CDN}/tJRopNNyzRnGEujP.mp3`,
    audioUrlAlt: `${CDN}/DnXVZsfYdJLIuoph.mp3`,
    theme: "viva",
  },
  {
    id: "t2-jpop-jp",
    title: "今夜はパーティー",
    style: "J-Pop",
    language: "日本語",
    flag: "🇯🇵",
    country: "Japão",
    neonColor: "#ff80ab",
    neonColorRgb: "255, 128, 171",
    audioUrl: `${CDN}/aQyLRXqguEuGYSNy.mp3`,
    audioUrlAlt: `${CDN}/MxELCLCKZUkTeONE.mp3`,
    theme: "viva",
  },
  {
    id: "t2-afrobeat-en",
    title: "Dance Am Oh",
    style: "Afrobeat",
    language: "Pidgin English",
    flag: "🇳🇬",
    country: "Nigéria",
    neonColor: "#ffd740",
    neonColorRgb: "255, 215, 64",
    audioUrl: `${CDN}/mTnBJjYLHOJAGRLb.mp3`,
    audioUrlAlt: `${CDN}/OcoAAXGzcEGffNxc.mp3`,
    theme: "viva",
  },
  {
    id: "t2-kpop-kr",
    title: "오늘 밤 파티",
    style: "K-Pop",
    language: "한국어",
    flag: "🇰🇷",
    country: "Coreia do Sul",
    neonColor: "#ea80fc",
    neonColorRgb: "234, 128, 252",
    audioUrl: `${CDN}/sQMJohxowwEDRsCE.mp3`,
    audioUrlAlt: `${CDN}/jRsUzSHNXLwBDHik.mp3`,
    theme: "viva",
  },
  {
    id: "t2-reggae-en",
    title: "Good Vibes Only",
    style: "Reggae",
    language: "English",
    flag: "🇯🇲",
    country: "Jamaica",
    neonColor: "#69f0ae",
    neonColorRgb: "105, 240, 174",
    audioUrl: `${CDN}/ueLwcsZvBALmjRNg.mp3`,
    audioUrlAlt: `${CDN}/oegBdvUiisqLRIyx.mp3`,
    theme: "viva",
  },
  {
    id: "t2-electronic-ar",
    title: "ارقص الليلة",
    style: "Eletrônica",
    language: "العربية",
    flag: "🇸🇦",
    country: "Arábia",
    neonColor: "#7c4dff",
    neonColorRgb: "124, 77, 255",
    audioUrl: `${CDN}/WPsmNDLuQuPVHciW.mp3`,
    audioUrlAlt: `${CDN}/lbmTJzwBzhKIOyOv.mp3`,
    theme: "viva",
  },
  {
    id: "t2-tango-ar",
    title: "Bailemos Esta Noche",
    style: "Tango",
    language: "Español",
    flag: "🇦🇷",
    country: "Argentina",
    neonColor: "#ff5252",
    neonColorRgb: "255, 82, 82",
    audioUrl: `${CDN}/lyETuWHAGvzURkkC.mp3`,
    audioUrlAlt: `${CDN}/BppqsNGPnmclOrvy.mp3`,
    theme: "viva",
  },
];

export function getTracksByTheme(theme: "se-olha" | "viva"): Track[] {
  return tracks.filter((t) => t.theme === theme);
}
